### ISSUE TITLE
vscode extension release automation

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#11]
We need to set up an automated process to package our VSCode extension and prepare it for publishing to both the VSCode Marketplace and the Open VSX Registry. This will ensure that every push to `main` and every new release results in a packaged extension, ready for installation and distribution.

### Tasks:

1. **Automated Packaging:**
   - Use **GitHub Actions** to automate packaging the extension on every push to the `main` branch and on every release.
   - We can leverage the `vsce` tool to handle the packaging of the extension.
     - [VSCE Documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
     - [VSCE GitHub](https://github.com/microsoft/vscode-vsce)
   - GitHub Actions documentation for reference:
     - [Creating GitHub Actions workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
     - [GitHub Actions for VSCode extensions](https://github.com/HaaLeo/publish-vscode-extension)

   **Steps to automate packaging:**
   - Set up a GitHub Actions workflow that runs on push to `main` and release events.
   - The workflow should:
     - Install dependencies (e.g., `npm install`).
     - Run `vsce package` to bundle the extension.
     - If required, create a release artifact for downloading the packaged `.vsix` file.

   Example GitHub Actions workflow:
   ```yaml
   name: Package VSCode Extension

   on:
     push:
       branches:
         - main
     release:
       types: [created]

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '16'

         - name: Install dependencies
           run: npm install

         - name: Package extension
           run: npx vsce package

         - name: Upload VSIX as artifact (optional)
           uses: actions/upload-artifact@v2
           with:
             name: my-extension
             path: '*.vsix'
   ```

2. **Publishing to the VSCode Marketplace:**
   - Create issues to handle the steps required for publishing to the VSCode Marketplace.
   - Publishing requires a publisher account and a Personal Access Token (PAT) from Azure DevOps to authenticate with the marketplace.
   - Documentation for publishing to the VSCode Marketplace:
     - [VSCode Publishing Documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
     - [Getting started with publishing](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#getting-started)
   - Steps include:
     - Setting up a publisher account.
     - Acquiring a Personal Access Token (PAT) from Azure DevOps.
     - Using the `vsce publish` command in the GitHub Actions workflow to automatically publish the extension.

   Example workflow snippet for publishing:
   ```yaml
   - name: Publish to VSCode Marketplace
     run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
   ```

3. **Publishing to the Open VSX Registry:**
   - Create issues for tracking the requirements to publish to Open VSX Registry.
   - Open VSX requires a publisher account as well and uses token-based authentication.
   - Documentation for publishing to Open VSX:
     - [Publishing to Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)
     - [Open VSX Documentation](https://open-vsx.org/extension/guide)
   - Steps include:
     - Creating an Open VSX publisher account.
     - Acquiring a token from the Open VSX registry.
     - Using the `ovsx` command in the GitHub Actions workflow to publish the extension.

   Example workflow snippet for publishing:
   ```yaml
   - name: Publish to Open VSX
     run: npx ovsx publish --pat ${{ secrets.OVSX_TOKEN }}
   ```

### Definition of Done:
- [ ] The extension is packaged on every push to `main` and on every release tag.
- [ ] GitHub Actions workflow to package and publish the extension is in place.
- [ ] All issues required for publishing to the VSCode Marketplace are created and tracked.
- [ ] All issues required for publishing to the Open VSX Registry are created and tracked.

**Comment by djzager** [comment]
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by djzager** [comment]
https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages
